version: '3.8'

# Services
services:

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server

    env_file: backend/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - ./../mydata:/data/db

# Volumes define
volumes:
  mydata: